version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: shoparize-challenge-php
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: shoparize-challenge-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: shoparize-challenge-redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge